---
# Automatically assign issues to users
#
# When new issues are created, they will automatically be assigned to a user.
#

name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  # See GitHub repository here: https://github.com/pozil/auto-assign-issue
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: gerph
          abortIfPreviousAssignees: true
          allowSelfAssign: true
